name:                vpf-tools
version:             0.1.2
github:              "biocom-uib/vpf"
license:             BSD3
author:              "Gabriel Riera"
maintainer:          "gabriel.riera@uib.es"
copyright:           "2019 Gabriel Riera"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Virus Protein Family tools
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/biocom-uib/vpf-tools#readme>

dependencies:
- base >= 4.7 && < 5
- Frames
- aeson
- array
- bytestring
- cryptonite
- constraints
- containers
- directory
- exceptions
- filepath
- foldl
- fused-effects
- kan-extensions
- lens
- lifted-async
- memory
- mmorph
- monad-control
- mtl
- optparse-applicative
- pipes
- pipes-concurrency
- pipes-group
- pipes-parse
- pipes-safe
- primitive
- profunctors
- reflection
- regex-base
- regex-pcre-builtin
- semigroupoids
- stm
- store
- tagged
- template-haskell
- temporary
- text
- transformers
- transformers-base
- typed-process
- vector
- vector-algorithms
- vinyl
- yaml

when:
- condition: flag(mpi)
  cpp-options: -DVPF_ENABLE_MPI
  dependencies:
  - mpi-hs

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

ghc-options:
  - -Wall
  - -Wno-unticked-promoted-constructors
  - -Wno-name-shadowing
  - -Werror=missing-fields
  - -Werror=missing-methods

library:
  source-dirs: src
  ghc-options:
  - -fsimpl-tick-factor=150

  when:
  - condition: flag(mpi)
    exposed-modules:
    - Control.Carrier.Distributed.MPI
    - Control.Distributed.MPI.Streaming

executables:
  vpf-class:
    main:                Main.hs
    source-dirs:         app/vpf-class
    when:
    - condition: flag(static)
      then:
        ghc-options: -threaded -rtsopts -with-rtsopts=-N -static
        ld-options: -static -pthread
        cc-options: -static
      else:
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - vpf-tools

  mpi-test:
    main:                Main.hs
    source-dirs:         app/mpi-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vpf-tools
    when:
    - condition: flag(mpi)
      then:
        buildable: true
      else:
        buildable: false

  pipes-test:
    main:                Main.hs
    source-dirs:         app/pipes-test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vpf-tools

tests:
  vpf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vpf-tools


flags:
  mpi:
    description: Enable MPI support (OpenMPI with mpi-hs)
    manual: true
    default: false

  static:
    description: Build static executables
    manual: true
    default: false
