name:                vpf-tools
version:             1.0.0.0
github:              "biocom-uib/vpf"
license:             BSD3
author:              "Gabriel Riera"
maintainer:          "gabriel.riera@uib.es"
copyright:           "2019 Gabriel Riera"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Virus Protein Family tools
category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/biocom-uib/vpf-tools#readme>

dependencies:
- base >= 4.7 && < 5
- Frames
- aeson
- array
- attoparsec
- bytestring
- conduit
- constraints
- containers
- cryptonite
- directory
- exceptions
- feed
- filepath
- foldl
- ftp-client
- ftp-client-conduit
- fused-effects
- kan-extensions
- lens
- lifted-async
- memory
- mmorph
- modern-uri
- monad-control
- mtl
- optparse-applicative
- primitive
- profunctors
- reflection
- regex-base
- regex-pcre-builtin
- resourcet
- req
- semigroupoids
- stm
- store
- streaming
- streaming-attoparsec
- streaming-bytestring
- streaming-concurrency
- streaming-utils
- tagged
- tar
- template-haskell
- temporary
- text
- these
- time
- transformers
- transformers-base
- typed-process
- vector
- vector-algorithms
- vinyl
- xlsx
- yaml
- zlib

when:
- condition: flag(mpi)
  cpp-options: -DVPF_ENABLE_MPI
  dependencies:
  - mpi-hs
  - mpi-hs-store

default-extensions:
- BangPatterns
- BlockArguments
- ConstraintKinds
- DataKinds
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- StandaloneKindSignatures
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

ghc-options:
  - -Wall
  - -Wno-unticked-promoted-constructors
  - -Wno-name-shadowing
  - -Werror=missing-fields
  - -Werror=missing-methods

library:
  source-dirs: src
  ghc-options:
  - -fsimpl-tick-factor=150

  when:
  - condition: flag(mpi)
    exposed-modules:
    - Control.Carrier.Distributed.MPI
    - Control.Distributed.MPI.Streaming

executables:
  vpf-class:
    main:                Main.hs
    source-dirs:         app/vpf-class
    when:
    - condition: flag(static)
      then:
        ghc-options: -threaded -rtsopts -with-rtsopts=-N -static
        ld-options: -static -pthread
        cc-options: -static
      else:
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - vpf-tools

  #mpi-test:
  #  main:                Main.hs
  #  source-dirs:         app/mpi-test
  #  ghc-options:
  #  - -threaded
  #  - -rtsopts
  #  - -with-rtsopts=-N
  #  dependencies:
  #  - vpf-tools
  #  when:
  #  - condition: flag(mpi)
  #    then:
  #      buildable: true
  #    else:
  #      buildable: false

  #pipes-test:
  #  main:                Main.hs
  #  source-dirs:         app/pipes-test
  #  ghc-options:
  #    - -threaded
  #    - -rtsopts
  #    - -with-rtsopts=-N
  #  dependencies:
  #    - vpf-tools

tests:
  vpf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vpf-tools


flags:
  mpi:
    description: Enable MPI support (OpenMPI with mpi-hs)
    manual: true
    default: true

  static:
    description: Build static executables
    manual: true
    default: false
